= NHL Statistics
Patrick Grimard <pgrimard@gmail.com>
v1.0.0, 2016-03-12
:toc:
:imagesdir: assets/images
:homepage: http://patrickgrimard.com

This service is used as a gateway to fetch statistics from the NHL website.  Although you could call the various endpoints
that NHL exposes directly, the goal of this project is to keep a consistent API in the event the NHL endpoints change.

== Endpoints

=== Players

[source]
----
/players?seasonId=20152016&gameTypeId=2
----

This endpoint returns player stats for the given `seasonId` and `gameTypeId`.

1. `seasonId` = The season requested, ex: `20152016`
2. `gameTypeId` = The game type requested, regular season is `2` while playoff season is `3`

=== Teams

[source]
----
/teams?seasonId=20152016
----

This endpoint returns team stats for the given `seasonId`.

1. `seasonId` = The season requested, ex: `20152016`

== Cloud

This application will attempt to register with a Eureka server at `http://localhost:8761`.  If a config server is
found and it contains `stats.api.players` and `stats.api.teams` properties, those will be used as the base URI for fetching
statistics.  If a Eureka server or config server is not available, then local properties should be configured.

=== Example

[source]
----
stats:
  api:
    players: http://www.nhl.com/stats/rest/skaters?reportType=basic&reportName=skatersummary
    teams: https://statsapi.web.nhl.com/api/v1/standings
----


== Troubleshooting NHL Endpoints

These are the underlying endpoints called by this service.  These may be useful if you need to make sure the NHL service
is still operating correctly, or if they've made changes, as they seem to do every year.

1. Team regular season stats - https://statsapi.web.nhl.com/api/v1/standings?season=20152016
2. Player regular season stats - http://www.nhl.com/stats/rest/grouped/skaters/season/skatersummary?cayenneExp=seasonId=20152016%20and%20gameTypeId=2
3. Player playoff season stats - http://www.nhl.com/stats/rest/grouped/skaters/season/skatersummary?cayenneExp=seasonId=20152016%20and%20gameTypeId=3