= NHL Statistics
Patrick Grimard <pgrimard@gmail.com>
v1.0.0, 2016-03-12
:toc:
:imagesdir: assets/images
:homepage: http://patrickgrimard.com

== REST Endpoints

=== Players

[source]
----
/players?seasonId=20152016&gameTypeId=2
----

This endpoint returns player stats for the given `seasonId` and `gameTypeId`.

1. `seasonId` = The season requested, ex: `20152016`
2. `gameTypeId` = The game type requested, regular season is `2` while playoff season is `3`

=== Teams

[source]
----
/teams?seasonId=20152016&gameTypeId=2
----

This endpoint returns team stats for the given `seasonId` and `gameTypeId`.

1. `seasonId` = The season requested, ex: `20152016`
2. `gameTypeId` = The game type requested, regular season is `2` while playoff season is `3`

== Cloud

This application will attempt to register with a Eureka server at `http://localhost:8761`.  If a config server is
found and it contains `stats.players` and `stats.teams` properties, those will be used as the base URI for fetching
statistics.  If a Eureka server or config server is not available, then local properties should be configured.

=== Example

[source]
----
stats:
  players: http://www.nhl.com/stats/rest/grouped/skaters/season/skatersummary
  teams: http://www.nhl.com/stats/rest/grouped/teams/season/teamsummary
----


== Troubleshooting NHL Endpoints

These are the underlying endpoints called by this service.  These may be useful if you need to make sure the NHL service
is still operating correctly, or if they've made changes, as they seem to do every year.

1. Team regular season stats - http://www.nhl.com/stats/rest/grouped/teams/season/teamsummary?cayenneExp=seasonId=20152016%20and%20gameTypeId=2
2. Team playoff season stats - http://www.nhl.com/stats/rest/grouped/teams/season/teamsummary?cayenneExp=seasonId=20152016%20and%20gameTypeId=3
3. Player regular season stats - http://www.nhl.com/stats/rest/grouped/skaters/season/skatersummary?cayenneExp=seasonId=20152016%20and%20gameTypeId=2
4. Player playoff season stats - http://www.nhl.com/stats/rest/grouped/skaters/season/skatersummary?cayenneExp=seasonId=20152016%20and%20gameTypeId=3